=== therealchalz/tunneller/tunneller.dtd
<!--
Copyright (c) 2013 Charles Hache <chalz@member.fsf.org>. All rights reserved. 

This file is part of the tunneller project.
tunneller is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

tunneller is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with tunneller.  If not, see <http://www.gnu.org/licenses/>.

Contributors:
    Charles Hache <chalz@member.fsf.org> - initial API and implementation
-->
<!ELEMENT tunneller (tunnel*)>

<!ELEMENT tunnel (user,host,port?,(password|(keyfile,passphrase?)),retryIntervalMs?,forward*)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT keyfile (#PCDATA)>
<!ELEMENT passphrase (#PCDATA)>
<!ELEMENT retryIntervalMs (#PCDATA)>

<!ELEMENT forward (localPort,host,remotePort)>
<!ATTLIST forward type (local|L|remote|R) #REQUIRED>
<!ELEMENT localPort (#PCDATA)>
<!ELEMENT remotePort (#PCDATA)>

=== therealchalz/tunneller/tunneller.xml
<!--
  Copyright (c) 2013 Charles Hache <chalz@member.fsf.org>. All rights reserved. 
  
  This file is part of the tunneller project.
  tunneller is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  tunneller is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with tunneller.  If not, see <http://www.gnu.org/licenses/>.
  
  Contributors:
      Charles Hache <chalz@member.fsf.org> - initial API and implementation
-->
<!DOCTYPE tunneller SYSTEM "tunneller.dtd">
<tunneller>
	<tunnel>
		<user>logger</user>
		<host>192.168.69.21</host>
		<password>wordofpass</password> <!-- or <keyfile> element -->
		<!--
		<keyfile>ssh/id_rsa</keyfile>
		-->
		<retryIntervalMs>10000</retryIntervalMs>
		<forward type="L">
			<localPort>8085</localPort>
			<host>127.0.0.1</host>
			<remotePort>80</remotePort>
		</forward>
		<forward type="R">
			<localPort>502</localPort>
			<host>127.0.0.1</host>
			<remotePort>8502</remotePort>
		</forward>
	</tunnel>
	<tunnel>
		<user>logger</user>
		<host>192.168.69.21</host>
		<password>wordofpass</password>
		<forward type="L">
			<localPort>8086</localPort>
			<host>127.0.0.1</host>
			<remotePort>80</remotePort>
		</forward>
		<forward type="R">
			<localPort>503</localPort>
			<host>127.0.0.1</host>
			<remotePort>8503</remotePort>
		</forward>
	</tunnel>
</tunneller>
